//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusiSoft.Data.EF.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusiSoftBDEntities : DbContext
    {
        public MusiSoftBDEntities()
            : base("name=MusiSoftBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaigns> Campaigns { get; set; }
        public virtual DbSet<CampaignsCustomers> CampaignsCustomers { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<MusicGenres> MusicGenres { get; set; }
        public virtual DbSet<Supports> Supports { get; set; }
        public virtual DbSet<SupportTypes> SupportTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
