//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusiSoft.Data.EF.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicGenres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicGenres()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CampaignId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
        public virtual Campaigns Campaigns { get; set; }
    }
}
