//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusiSoft.Data.EF.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supports
    {
        public int Id { get; set; }
        public int SupportTypeId { get; set; }
        public int CompanyId { get; set; }
        public string AplicantName { get; set; }
        public string AplicantIdentification { get; set; }
        public string AplicantEmail { get; set; }
        public string AplicantPhone { get; set; }
        public string Description { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual SupportTypes SupportTypes { get; set; }
    }
}
